# http listen port:
port: 8080

# uncomment for https:
#https:
#  port: 8443
#  cert: /path/to/cert.pem
#  key: /path/to/key.pem

# dev or prod. in prod mode the logs will not include requests ip addresses
mode: dev

content:
  title:
    de: Meldeplattform
    en: Reporting Platform
  subtitle:
    de: Technische Universität München
    en: Technical University of Munich
  logo:
    <svg xmlns:svg="http://www.w3.org/2000/svg" width="100px" xmlns="http://www.w3.org/2000/svg" viewBox="-16.014 -31 408.16 212.46684" enable-background="new -16.014 -31 149 114" xml:space="preserve" sodipodi:docname="TUM_Web_Logo_blau.svg" inkscape:version="1.0.1 (3bc2e813f5, 2020-09-07)"><metadata id="metadata13"><rdf:RDF><cc:Work rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/><dc:title>TUM_Web_Logo_blau</dc:title></cc:Work></rdf:RDF></metadata><defs id="defs11"/><sodipodi:namedview pagecolor="#ffffff" bordercolor="#666666" borderopacity="1" objecttolerance="10" gridtolerance="10" guidetolerance="10" inkscape:pageopacity="0" inkscape:pageshadow="2" inkscape:window-width="1920" inkscape:window-height="986" id="namedview9" showgrid="false" fit-margin-top="0" fit-margin-left="0" fit-margin-right="0" fit-margin-bottom="0" inkscape:zoom="1.754386" inkscape:cx="124.61021" inkscape:cy="115.2546" inkscape:window-x="-11" inkscape:window-y="-11" inkscape:window-maximized="1" inkscape:current-layer="Ebene_1"/>
    <path fill="#3070b3" d="m 140.54052,-31 v 173.32822 h 44.72985 V -31 H 392.146 V 181.46685 H 353.00738 V 8.138629 H 308.2775 V 181.46685 H 269.13887 V 8.138629 H 224.40902 V 181.46685 H 101.4019 V 8.138629 H 62.26327 V 181.46685 H 23.12462 V 8.138629 H -16.014 V -31 Z" id="path6" style="stroke-width:5.59123"/>
    </svg>
  adminUsers:
    - "ge25bof"

# uploads are saved here:
fileDir: files
URL: http://localhost:8080

saml:
  idpMetadataURL: https://login.tum.de/idp/shibboleth
  #cert: /path/to/fullchain.pem
  #privkey: /path/to/privkey.pem
  entityID: https://meldeplattform.tum.de/shib
  rootURL: https://meldeplattform.tum.de/shib
  cert:
    org: "TUM"
    country: "DE"
    province: "BY"
    locality: "Munich"
    streetAddress: "Arcisstr. 21"
    postalCode: "80333"
    cn: "meldeplattform.tum.de"

mail:
  user: "ge42tum"
  password: "abc123"
  smtpServer: "smtp.tum.de"
  smtpPort: "587"
  from: "meldeplattform@tum.de"
  fromName: "Meldeplattform TUM"

imprint: |
  # Impressum

  Angaben gemäß § 5 TMG

  Redaktionell verantwortlich für den Inhalt dieser Webseite ist Michael Strobel: [IT Management - TUM IT - CIO](https://www.it.tum.de/it/it-servicezentrum/it-management/).

  Datenschutzbeauftragt ist der/die Datenschutzbeauftragte der TUM: [Startseite - Datenschutz](https://www.datenschutz.tum.de/datenschutz/startseite/)

  ---

  ## Haftung für Inhalte

  Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die 
  Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir 
  jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 
  Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen 
  Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als 
  Diensteanbieter jedoch nicht verpflichtet, übermittelte oder 
  gespeicherte fremde Informationen zu überwachen oder nach Umständen zu 
  forschen, die auf eine rechtswidrige Tätigkeit hinweisen. 
  Verpflichtungen zur Entfernung oder Sperrung der Nutzung von 
  Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. 
  Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der 
  Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von
   entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend 
  entfernen.

  ## Haftung für Links

  Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte 
  wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte 
  auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist 
  stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. 
  Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche 
  Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der 
  Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der 
  verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer 
  Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von 
  Rechtsverletzungen werden wir derartige Links umgehend entfernen.

  ## Datenschutz

  Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener
   Daten möglich. Soweit auf unseren Seiten personenbezogene Daten 
  (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, 
  erfolgt dies stets auf freiwilliger Basis. Diese Daten 
  werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.
  Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei 
  der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein 
  lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht 
  möglich.
  Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten 
  Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich 
  angeforderter Werbung und Informationsmaterialien wird hiermit 
  ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich 
  ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von
   Werbeinformationen, etwa durch Spam-Mails, vor.

  Welche Daten erhoben und verarbeitet werden, beschreibt die [Datenschutzerklärung](https://nav.tum.de/about/datenschutz).

  *Auszüge aus diesem Impressum wurden mithilfe des [Impressums Generator](https://www.impressum-generator.de) der [Kanzlei Hasselbach, Rechtsanwälte für Arbeitsrecht und Familienrecht](https://www.kanzlei-hasselbach.de/) erstellt.*

privacy: |
  # Datenschutzerklärung

  ## Verantwortlicher

  Verantwortlicher im Sinne der Datenschutzgesetze, insbesondere der EU-Datenschutzgrundverordnung (DSGVO), ist der/die Datenschutzbeauftragte der TUM: [Startseite - Datenschutz](https://www.datenschutz.tum.de/datenschutz/startseite/)

  **Postanschrift:**  
  Technische Universität München
  
  Arcisstr. 21
  
  80333 München
  
  Deutschland

  ## Ihre Betroffenenrechte

  Unter den angegebenen Kontaktdaten unseres Datenschutzbeauftragten können Sie jederzeit folgende Rechte ausüben:

  - Auskunft über Ihre bei uns gespeicherten Daten und deren Verarbeitung (Art. 15 DSGVO),
  - Berichtigung unrichtiger personenbezogener Daten (Art. 16 DSGVO),
  - Löschung Ihrer bei uns gespeicherten Daten (Art. 17 DSGVO),
  - Einschränkung der Datenverarbeitung, sofern wir Ihre Daten aufgrund gesetzlicher 
    Pflichten noch nicht löschen dürfen (Art. 18 DSGVO),
  - Widerspruch gegen die Verarbeitung Ihrer Daten bei uns (Art. 21 DSGVO) und
  - Datenübertragbarkeit, sofern Sie in die Datenverarbeitung eingewilligt haben oder einen Vertrag mit uns abgeschlossen haben (Art. 20 DSGVO).

  Sofern Sie uns eine Einwilligung erteilt haben, können Sie diese jederzeit mit Wirkung für die Zukunft widerrufen.
  Sie können sich jederzeit mit einer Beschwerde an eine Aufsichtsbehörde wenden, z. B. an die zuständige Aufsichtsbehörde
  des Bundeslands Ihres Wohnsitzes oder an die für uns als verantwortliche Stelle zuständige Behörde.
  Eine Liste der Aufsichtsbehörden (für den nicht öffentlichen Bereich) 
  mit Anschrift finden Sie unter: [BfDI - Landesbehörden](https://www.bfdi.bund.de/DE/Service/Anschriften/Laender/Laender-node.html).

  ## Technische Umsetzung

  Der Webserver wird betrieben durch die Rechnerbetriebsgruppe der School of Computation, Information and Technology an der TUM, Boltzmannstr. 3, 85748 Garching bei München, Deutschland. Die Beauftragung erfolgt auf Grundlage unserer 
  berechtigten Interessen gem. Art. 6 Abs. 1 lit. f DSGVO und eines Auftragsverarbeitungsvertrages gem. Art. 28 Abs. 3 S. 1 DSGVO.

  ## Protokollierung

  Wenn Sie diese oder andere Internetseiten aufrufen, übermitteln Sie über 
  Ihren Internetbrowser Daten an unseren Webserver. Die folgenden Daten 
  werden während einer laufenden Verbindung zur Kommunikation zwischen 
  Ihrem Internetbrowser und unserem Webserver aufgezeichnet:

  - Datum und Uhrzeit der Anfrage
  - Zeitbetrag, den die Anfrage gedauert hat
  - Name der angeforderten Datei
  - Seite, von der aus die Datei angefordert wurde
  - Zugriffsstatus (Datei übertragen, Datei nicht gefunden, etc.)
  - verwendete Webbrowser und verwendetes Betriebssystem
  - übertragene Datenmenge.

  Insbesondere werden keine IP-Adressen protokolliert.

  Die Logeinträge werden kontinuierlich automatisch ausgewertet, um Angriffe auf die Webserver erkennen und entsprechend reagieren zu können.
  In Einzelfällen, d.h. bei gemeldeten Störungen, Fehlern und Sicherheitsvorfällen, erfolgt eine manuelle analyse.
  Logeinträge werden nach maximal 2 Wochen automatisiert gelöscht.

  ## Cookies

  Wie viele andere Webseiten verwenden wir auch sogenannte „Cookies“. Bei 
  Cookies handelt es sich um kleine Textdateien, die auf Ihrem Endgerät 
  (Laptop, Tablet, Smartphone o.ä.) gespeichert werden, wenn Sie unsere 
  Webseite besuchen.

  Sie können Sie einzelne Cookies oder den gesamten Cookie-Bestand löschen. Darüber hinaus erhalten Sie Informationen und Anleitungen, wie diese Cookies gelöscht oder deren Speicherung vorab blockiert werden können. Je nach Anbieter Ihres Browsers finden Sie die notwendigen Informationen unter den nachfolgenden Links:

  - Mozilla Firefox: https://support.mozilla.org/de/kb/cookies-loeschen-daten-von-websites-entfernen
  - Internet Explorer: [Löschen und Verwalten von Cookies - Microsoft-Support](https://support.microsoft.com/de-de/help/17442/windows-internet-explorer-delete-manage-cookies)
  - Google Chrome: [Cookies aktivieren oder deaktivieren - Computer - Google-Konto-Hilfe](https://support.google.com/accounts/answer/61416?hl=de)
  - Opera: [Probleme mit dem Browser? Wir können Ihnen helfen! | Hilfe und Häufig gestellte Fragen (FAQ) | Opera](http://www.opera.com/de/help)
  - Safari: https://support.apple.com/kb/PH17191?locale=de_DE&viewlocale=de_DE

  ### Technisch notwendige Cookies - Art und Zweck der Verarbeitung:

  Wir setzen Cookies ein, um unsere Website nutzerfreundlicher zu gestalten. 
  Einige Elemente unserer Internetseite erfordern es, dass vom Benutzer 
  gewählte Einstellungen auch nach einem Seitenwechsel vorhanden sind.
  Der Zweck der Verwendung technisch notwendiger Cookies ist, die Nutzung 
  von Websites für die Nutzer zu vereinfachen. Einige Funktionen unserer 
  Internetseite können ohne den Einsatz von Cookies nicht angeboten 
  werden.

  Für folgende Anwendungen benötigen wir Cookies:

  - Übernahme von Spracheinstellungen
  - Session nach optionalem Login auf der Seite fuer administrative Nutzer

  Diese Webseite verwendet diese Cookies ausschließlich zum Zwecke der 
  Speicherung der Sprachen- und Theme-Einstellung. Ein entsprechendes, 
  nicht-personenbezogenes, Cookie wird erst gesetzt, wenn die 
  Standardeinstellung geändert wird.

  ### Speicherdauer

  Die Cookies werden serverseitig nicht protokolliert oder gespeichert. Daher ist kein Tracking über Cookies möglich.
  Im Browser beträgt die Speicherdauer eine Woche.

  ### Übertragene Daten

  Bei der Kontaktaufnahme mit uns per Feedbackformular werden die Angaben des Nutzers zur Bearbeitung der Kontaktanfrage und deren Abwicklung gem. 
  Art. 6 Abs. 1 lit. b) DSGVO verarbeitet.
  Eine Rückführung auf die Person ist dabei nur insoweit möglich, wie personenbezogene Daten im versendeten Text enthalten sind.
  Neben dem vom Nutzer bereitgestellten Daten wird außerdem das Datum und die Uhrzeit der Feedbackserstellung gesendet.

  ### Empfänger:

  Empfänger der vom Nutzer bereitgestellten Daten ist auf den jeweiligen Eingabeformularen angegeben.

  ### Speicherdauer:

  Die Daten von einem Nutzer freiwillig bereitgestellten Daten werden technisch nicht gelöscht, außer er wünscht dies.

  ### Bereitstellung vorgeschrieben oder erforderlich:

  Die Bereitstellung dieser nicht personenbezogenen Daten erfolgt freiwillig.

  ## SSL-Verschlüsselung

  Um die Sicherheit Ihrer Daten bei der Übertragung zu schützen, verwenden wir dem aktuellen Stand der Technik entsprechende Verschlüsselungsverfahren (TLS).

  ## Information über Ihr Widerspruchsrecht nach Art. 21 DSGVOEinzelfallbezogenes Widerspruchsrecht

  Sie haben das Recht, aus Gründen, die sich aus Ihrer besonderen Situation 
  ergeben, jederzeit gegen die Verarbeitung Sie betreffender 
  personenbezogener Daten, die aufgrund Art. 6 Abs. 1 lit. f DSGVO 
  (Datenverarbeitung auf der Grundlage einer Interessenabwägung) erfolgt, 
  Widerspruch einzulegen; dies gilt auch für ein auf diese Bestimmung 
  gestütztes Profiling im Sinne von Art. 4 Nr. 4 DSGVO.
  Legen Sie Widerspruch ein, werden wir Ihre personenbezogenen Daten nicht
   mehr verarbeiten, es sei denn, wir können zwingende schutzwürdige 
  Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und 
  Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, 
  Ausübung oder Verteidigung von Rechtsansprüchen.

  ### Empfänger eines Widerspruchs

  Bitte nutzen Sie die im Impressum genannten Kontaktmöglichkeiten

  ## Änderung unserer Datenschutzbestimmungen

  Wir behalten uns vor, diese Datenschutzerklärung anzupassen, damit sie 
  stets den aktuellen rechtlichen Anforderungen entspricht oder um 
  Änderungen unserer Leistungen in der Datenschutzerklärung umzusetzen, 
  z.B. bei der Einführung neuer Services. Für Ihren erneuten Besuch gilt 
  dann die neue Datenschutzerklärung.

  ## Fragen an den Datenschutzbeauftragten

  Wenn Sie Fragen zum Datenschutz haben, schreiben Sie uns bitte eine E-Mail 
  oder wenden Sie sich direkt an die für den Datenschutz verantwortliche 
  Person in unserer Organisation. Diese Person finden Sie unter den im 
  Impressum genannten Kontaktmöglichkeiten.

  *Auszüge aus dieser Datenschutzerklärung wurden mithilfe der activeMind AG erstellt,
  den Experten für [externe Datenschutzbeauftragte](https://www.activemind.de/datenschutz/datenschutzbeauftragter/) (Version #2020-09-30).
