# http listen port:
port: 8080

# uncomment for https:
#https:
#  port: 8443
#  cert: /path/to/cert.pem
#  key: /path/to/key.pem

# dev or prod. in prod mode the logs will not include requests ip addresses
mode: dev

content:
  title:
    de: Meldeplattform
    en: Reporting Platform
  subtitle:
    de: Technische Universität München
    en: Technical University of Munich
  logo:
    <svg xmlns:svg="http://www.w3.org/2000/svg" width="100px" xmlns="http://www.w3.org/2000/svg" viewBox="-16.014 -31 408.16 212.46684" enable-background="new -16.014 -31 149 114" xml:space="preserve" sodipodi:docname="TUM_Web_Logo_blau.svg" inkscape:version="1.0.1 (3bc2e813f5, 2020-09-07)"><metadata id="metadata13"><rdf:RDF><cc:Work rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/><dc:title>TUM_Web_Logo_blau</dc:title></cc:Work></rdf:RDF></metadata><defs id="defs11"/><sodipodi:namedview pagecolor="#ffffff" bordercolor="#666666" borderopacity="1" objecttolerance="10" gridtolerance="10" guidetolerance="10" inkscape:pageopacity="0" inkscape:pageshadow="2" inkscape:window-width="1920" inkscape:window-height="986" id="namedview9" showgrid="false" fit-margin-top="0" fit-margin-left="0" fit-margin-right="0" fit-margin-bottom="0" inkscape:zoom="1.754386" inkscape:cx="124.61021" inkscape:cy="115.2546" inkscape:window-x="-11" inkscape:window-y="-11" inkscape:window-maximized="1" inkscape:current-layer="Ebene_1"/>
    <path fill="#3070b3" d="m 140.54052,-31 v 173.32822 h 44.72985 V -31 H 392.146 V 181.46685 H 353.00738 V 8.138629 H 308.2775 V 181.46685 H 269.13887 V 8.138629 H 224.40902 V 181.46685 H 101.4019 V 8.138629 H 62.26327 V 181.46685 H 23.12462 V 8.138629 H -16.014 V -31 Z" id="path6" style="stroke-width:5.59123"/>
    </svg>
  adminUsers:
    - "ge42tum"

# uploads are saved here:
fileDir: files
URL: http://localhost:8080

saml:
  idpMetadataURL: https://login.tum.de/idp/shibboleth
  #cert: /path/to/fullchain.pem
  #privkey: /path/to/privkey.pem
  entityID: https://meldeplattform.tum.de/shib
  rootURL: https://meldeplattform.tum.de/shib
  cert:
    org: "TUM"
    country: "DE"
    province: "BY"
    locality: "Munich"
    streetAddress: "Arcisstr. 21"
    postalCode: "80333"
    cn: "meldeplattform.tum.de"

mail:
  user: "ge42tum"
  password: "abc123"
  smtpServer: "smtp.tum.de"
  smtpPort: "587"
  from: "meldeplattform@tum.de"
  fromName: "Meldeplattform TUM"
